baseurl = "https://official-stallion.github.io/website/"
languageCode = "en-us"
paginate = 5

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 2
  fullWidthTheme = true
  centerTheme = true

[languages]
  [languages.en]
    title = "Stallion"
    subtitle = "A fast message broker implemented with Golang"
    keywords = "stallion,go,golang"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Stallion"
      logoHomeLink = "/website"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "docs"
        name = "Docs"
        url = "/docs"
      [[languages.en.menu.main]]
        identifier = "components"
        name = "Components"
        url = "/components"
