apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-golang
  labels:
    app: k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
      - name: k8s
        image: amirhossein21/k8s-golang
        ports:
        - containerPort: 80