apiVersion: v1
kind: Pod
metadata:
  name: k8s-golang
  labels:
    name: k8s-golang
spec:
  containers:
  - name: k8s-golang-container
    image: amirhossein21/k8s-golang
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
        protocol: TCP
